=== api-evangelist/argyle/json-schema/clientuser.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argyle/refs/heads/main/json-schema/clientuser.json",
  "title": "ClientUser",
  "type": "object",
  "description": "Client user object.",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "Unique ID of the user."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) when the user was created."
    },
    "items_connected": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Items the user has connected through Link."
    },
    "employers_connected": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Employers associated with the connected items."
    },
    "first_name": {
      "type": "string",
      "description": "User first name."
    },
    "last_name": {
      "type": "string",
      "description": "User last name."
    },
    "email": {
      "type": "string",
      "description": "User email address."
    },
    "phone_number": {
      "type": "string",
      "description": "User phone number."
    },
    "ssn": {
      "type": "string",
      "description": "User Social Security number."
    },
    "address": {
      "$ref": "#/components/schemas/ClientAddress"
    },
    "birth_date": {
      "$ref": "#/components/schemas/ClientBirthDate"
    },
    "external_metadata": {
      "type": "object",
      "description": "Additional metadata for internal workflows.",
      "additionalProperties": true
    },
    "external_id": {
      "type": "string",
      "nullable": true,
      "description": "External identifier for your internal mapping."
    }
  }
}

=== api-evangelist/argyle/examples/patch-partners-v2-users-{id}-response-200.json
{
  "id": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T04:54:35.170468Z",
  "items_connected": [
    "item_123456789",
    "item_987654321"
  ],
  "employers_connected": [
    "Whole Goods",
    "Bullseye"
  ],
  "first_name": "Jane",
  "last_name": "Doe",
  "ssn": "000-00-0000",
  "email": "jane@example.com",
  "phone_number": "+15555555555",
  "address": {
    "city": "New York",
    "line1": "123 Main St",
    "line2": null,
    "state": "NY",
    "country": "US",
    "postal_code": null
  },
  "birth_date": {
    "year": 1990,
    "month": 1,
    "day": 13
  },
  "external_metadata": {
    "suppress_verification": true,
    "additional_id": "123"
  },
  "external_id": "ABC"
}
