=== api-evangelist/argyle/json-schema/clientverification.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argyle/refs/heads/main/json-schema/clientverification.json",
  "title": "ClientVerification",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "format": "uuid",
      "description": "Unique ID of the verification."
    },
    "user": {
      "type": "string",
      "format": "uuid",
      "description": "ID of the user associated with the verification."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) when the verification was requested."
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)) when the verification object was last updated."
    },
    "channel": {
      "type": "string",
      "enum": [
        "api",
        "encompass"
      ],
      "example": "api",
      "description": "Origin of the verification order."
    },
    "status": {
      "$ref": "#/components/schemas/ClientVerificationStatus"
    },
    "report": {
      "$ref": "#/components/schemas/ClientVerificationReport"
    },
    "employments": {
      "type": "array",
      "description": "List of employments for the user. Documents only.",
      "items": {
        "$ref": "#/components/schemas/ClientVerificationEmployment"
      }
    },
    "loan": {
      "$ref": "#/components/schemas/ClientVerificationLoan"
    },
    "billing": {
      "$ref": "#/components/schemas/ClientVerificationBilling"
    },
    "data_source": {
      "type": "string",
      "enum": [
        "payroll",
        "banking",
        "documents"
      ],
      "description": "Source of verification data."
    }
  }
}

=== api-evangelist/argyle/examples/get-v2-verifications-{id}-response-200.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PROCESSING",
    "code": "authenticated",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "voai",
    "file_url": null,
    "json_url": null,
    "configuration": {
      "from_date": "2024-01-01T00:00:00Z",
      "income_stream_confidence_minimum": 50,
      "report_custom_fields": [
        {
          "label": "loanID",
          "value": "12345",
          "shown": true
        }
      ]
    }
  },
  "employments": [],
  "loan": {
    "number": "1234",
    "borrower_id": "ABC789",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "5"
  },
  "data_source": "banking"
}

=== api-evangelist/argyle/examples/patch-v2-verifications-{id}-response-200-documents.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PROCESSING",
    "code": "documents_processing",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "doc-voi-mortgage",
    "file_url": null,
    "json_url": null
  },
  "employments": [
    {
      "employer": "Warehouse Services Inc",
      "status": "previous",
      "hire_date": "2015-08-28",
      "termination_date": "2023-05-01"
    },
    {
      "employer": "Amazon",
      "status": "active",
      "hire_date": "2023-06-15",
      "termination_date": null
    }
  ],
  "loan": {
    "number": "1234",
    "borrower_id": "5678",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "5"
  },
  "data_source": "documents"
}

=== api-evangelist/argyle/examples/post-v2-verifications-response-200-documents.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PENDING",
    "code": "pending",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "doc-voi-mortgage",
    "file_url": null,
    "json_url": null
  },
  "employments": [
    {
      "employer": "Warehouse Services Inc",
      "status": "active",
      "hire_date": "2023-02-01",
      "termination_date": null
    }
  ],
  "loan": {
    "number": "1234",
    "borrower_id": "ABC789",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "5"
  },
  "data_source": "documents"
}

=== api-evangelist/argyle/examples/post-v2-verifications-refresh-response-200-banking.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PENDING",
    "code": "pending",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "voa",
    "file_url": null,
    "json_url": null,
    "configuration": {
      "from_date": "2025-01-01T00:00:00Z"
    }
  },
  "employments": [],
  "loan": {
    "number": "1234",
    "borrower_id": "ABC789",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "5"
  },
  "data_source": "banking"
}

=== api-evangelist/argyle/examples/patch-v2-verifications-{id}-response-200-payroll.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PROCESSING",
    "code": "authenticated",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "voie",
    "file_url": null,
    "json_url": null
  },
  "employments": [],
  "loan": {
    "number": "5678",
    "borrower_id": "5678",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "new_cost_center"
  },
  "data_source": "payroll"
}

=== api-evangelist/argyle/examples/post-v2-verifications-refresh-response-200-payroll.json
{
  "id": "43a2c6c3-1e63-91e5-88e3-f9ab2dcc489b",
  "user": "018051aa-f7a9-a0db-2f38-6cfa325e9d69",
  "created_at": "2023-03-09T16:22:06.081Z",
  "updated_at": "2023-03-09T16:22:06.081Z",
  "channel": "api",
  "status": {
    "state": "PENDING",
    "code": "pending",
    "errors": []
  },
  "report": {
    "id": null,
    "type": "voie",
    "file_url": null,
    "json_url": null
  },
  "employments": [],
  "loan": {
    "number": "1234",
    "borrower_id": "ABC789",
    "application_id": "2121313",
    "officer_email": "john.doe@mortgage.com"
  },
  "billing": {
    "cost_center": "5"
  },
  "data_source": "payroll"
}
